- name: article
  color: 54dd9b
  description: An article
- name: proposal
  color: '5319e7'
  description: Article Proposal
- name: question
  color: d876e3
  description: Ask the editors something
- name: complete
  color: c5def5
  description: An item that is complete
- name: stale
  color: d93f0b
  description: No recent updates have been made